server.port=8081
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.enabled=true
#file.dir=/usr/picture/save/
file.dir=C:\\Users\\Admin\\Pictures\\save\\
mybatis.configuration.map-underscore-to-camel-case=true