server.port=8081
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.enabled=true
file.dir=C:\\Users\\Admin\\Pictures\\save\\
mybatis.configuration.map-underscore-to-camel-case=true
script.path =/usr/app/py
output.dir =/usr/app/html
music.store =/usr/app/music
minio.enabled=false
db.model=doubao-seed-2-0-pro-260215
db.url=https://ark.cn-beijing.volces.com/api/v3"
