server.port=8081
spring.serverlet.multipart.max-file-size=10MB
spring.serverlet.multipart.max-request-size=10MB
#file.dir=/usr/picture/save/
file.dir=C:\\Users\\Admin\\Pictures\\save\\
mybatis.configuration.map-underscore-to-camel-case=true