spring:
  application:
    name: myApp
  redis:
    host: 192.168.146.100
    port: 6379
    password:
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
rocketmq:
  name-server: 192.168.146.100:9876
  producer:
     group: async-log-producer
     send-message-timeout: 3000
     compress-message-body-threshold: 4096
     retry-times-when-send-failed: 2
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
minio:
  endpoint: http://192.168.146.100:9000
  access-key: minio
  secret-key: Minio@123
  bucket: pic
server:
  tomcat:
    max-swallow-size: 10MB

alipay:
  app-id: 2021006131672288
  private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCLjTH3MzYivi4cMoa3I/i6fklHL4132wsC4BP64OaKL2YgFdp+a7/rydANg5mip0m687GWDaqr3rn348E7BWJOme3GzoyJAsbhpxTq8cTCLqlmhzqjm1s3shgom5YOjU4vTGq3Q9Fy2CcI110iXRi4s+fvBG7nAo4exHu/JZTwn8zF7mDdONWMtFhCyx2j5+pW0FjHSNKs37uaVFGKfyX7STr+ceput4wlrCh7tjbRlPwDTJO6/55yysmUY+Meld9dywxNY9lYp10gsCRsACUiz4scqr8/A++lum7XrFWUB3xwrXLf03XWwCAMgF21fhkwsSNdRUYnlzGQB+7bmpmdAgMBAAECggEAC+wZK7RdWKSEzfXnGnhhRJWLbyB55pZ5H1rDejiCmaWpBO65BvnvoJZSRwVKN+Iw4170egxa22og2zPDC2bPWkW+UbDNwtrQ4PBkUhorpCdWY6MD+HxKU7zMYZPBQycBWfseVt/dYgFjfFbh5xCrDwSXuQzY6LWILMq+g7sTOWddQ/B7zrcUyh1he+56gcaV//lP1rFjQHpm2hPrVuOqoxbzcz6zyt7sZKhCR0xM7iIyjQuL2uR3w563whBApZYSh0CoLgzgHyVXIfnfbIoZEKkzXWsfBigzVLX3QRvJxAqlz2wPYDJev+n6HT1woStVsQrjPLWnsn0NSsFoApsiBQKBgQDFzhOUK2kpvLo6JuPjb7DUahDxKY8t9Kief4FhikFXM5y+SPHe8UQA4HrBKMZZb9u7Z+tP/kEMEc05wiwU/49Fam0qX21V43HwZX1Av/ifT2rKbYsWAyHejGxVma+LpS4gNuRBmZIChkFl0DnYnPk0mm5TUjh8ikwG1h57VQMr7wKBgQC0m7CQST/Cb6HM2I5G8utVdBJmSjnCoNI8IN6rSfIc7khI2cv8+EZbsUBELwS0KnwufWGuQCLPpJeJqJwt3xKqt0dpvRVG3+ddIBuk4E/frnALgOBE/2HLAqitJp8QQw0IjOpOBalVlPQ7nrx9YvT3CqTULTWlE1xG8h5c5H+3MwKBgHpckZX+CK7t9ZGVjzGZXRz5hAN7PvwhtdFedM2+9c6YueSoQR81xmh4dNdafuDCpn3WuiUg1mI9/OM274gJ0zoQrPkiUQNpkIkybvoIByedvCT/AKQcSe5elYGacZKEGvWIn0jJVB5FqNzvo2kRKcPVqFvYp+K6tm8gM3j9zNl3AoGAD/YyhI30tJppElGRQXP2mHbJqYCl2i2cZvQAueKvIx9sBAQ7ov/OOAxSQbRmFgYrM3ChUWUZroA9ZE0igGtWmv/Xr+CmIL1pFTHhP5ETfhFMlbeuGmr3mZmCjsr7A9TpMfhCPOMDNC0V6K7+uZYlUDAAoT/dndk4Loz3Yf5Py0ECgYAqj+XGP7+VoBQD2OgzN0AEsebMG70D8jp2i01KIuZctlWn36kksWKU6wf2jYxO5z3DktpCmj2dE21FFkkltwUrZdFZ9RvyoPyjYfffX5j6aCRnVWTakMExd5K8E/undyHaXZkPj795aTbRt/ooIh4D8uQQlbAnOMD+Opu1NlnbQw==
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzfM814l4dFzk0rjVxWExCz1Fv6sfzbs9DkkJrW3jnhfD6dYVp3Q0VSmgRTVshsYTw85V2LsAZaU9rq6IkdY2jCmaIhFlQYxKMBSCYr8JdV4GR/Uxd+YYY9SEYMaU6yYNoxH7ZJq1qPtK1105d6pB9DnjtALnmabW9wPzRboTXQyKMPIGM/hMA7xjVpyGMU8VRi5WumHet77s3hjLnkJhJaOkKNyoSZHEpdOKZE8nX9IcYwxmNfYQXDK61yzqQ1CSDxYHVR9LPWMin2J5VxLpHbHfU554F4fxoRxxEviSkuZnJXzeqrz+cdgS1KNltgpajSks+iA59RBUxGRFlpteAQIDAQAB
  gateway-url: https://openapi.alipay.com/gateway.do
  notify-url: http://124.223.89.5/alipay/notify
